## 명명 패턴보다 애너테이션을 사용하라
### 명명 패턴
- 정해진 이름 규칙을 지키는 것 ```ex) Junit3까지의 메서드 이름 testXXX```
- 단점
  - 오타 나면 안된다.
  - 올바른 프로그램 요소에서만 사용되리라 보증할 방법이 없다.
    - ex) 클래스 이름에 적용하면 무시됨.
  - 프로그램 요소를 매개변수로 전달할 마땅한 방법이 없다.
    - ex) 특정 예외에 대한 테스트를 하고 싶어도, 기대하는 예외 타입을 전달할 수 없다.  

  **애너테이션 사용으로 해결**
### 애너테이션 동작 방식 예시
**예외가 발생하면 테스트 실패하는 경우**
```java
/*
        테스트 메서드임을 선언하는 애너테이션.
        매개변수 없는 정적 메서드 전용
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface PondTest { //아무런 매개변수 없이 단순히 대상에 마킹하는 마커 애너테이션
}

```
>메타 애너테이션 : 애너테이션 선언에 다는 애너테이션
> @Retention: 애너테이션이 유지되는 기간  
> @Target: 애너테이션을 붙일 수 있는 곳

```java
public class Sample {
    @PondTest
    public static void m1() {} //성공해야 한다.

    public static void m2() {}

    @PondTest
    public static void m3() { //실패해야 한다.
        throw new RuntimeException("실패");
    }

    @PondTest
    public void m5() {} //정적 메서드가 아니다.

    public static void m6() {}

    @PondTest
    public static void m7() { //실패해야 한다.
        throw new RuntimeException("실패");
    }

    public static void m8() {}
}
```
주석을 만족하려면 애너테이션 처리기 구현이 필요하다

```java
 public static void main(String[] args) throws Exception {
    int tests = 0;
    int passed = 0;
    Class<?> testClass = Class.forName("org.example.item39.Sample");
    for (Method m : testClass.getDeclaredMethods()) {
        if (m.isAnnotationPresent(PondTest.class)) {
            tests++;
            try {
                m.invoke(null);
                passed++;
            } catch (InvocationTargetException wrappedExc) {
                Throwable exc = wrappedExc.getCause();
                System.out.println(m + " 실패: " + exc);
            } catch (Exception exc) {
                System.out.println("잘못 사용한 @Test: " + m);
            }
        }
    }
    System.out.printf("성공: %d, 실패: %d%n", passed, tests - passed);
}
    /*
      public static void org.example.item39.Sample.m3() 실패: java.lang.RuntimeException: 실패
      잘못 사용한 @Test: public void org.example.item39.Sample.m5()
      public static void org.example.item39.Sample.m7() 실패: java.lang.RuntimeException: 실패
      성공: 1, 실패: 3
    */
```
- getDeclaredMethods로 클래스에 정의된 모든 메서드 호출
- isAnnotationPresent로 전달된 애너테이션이 붙어있는 지 확
- invoke를 통해 불러온 메서드 실행
- invoke를 통해 실행된 메서드 내에서 발생한 예외는 InvocationTargetException으로 감싸져 던져진다.
- InvocationTargetException 외의 예외가 발생하면 애너테이션을 잘못 사용했다는 의미(예시에서는 인스턴스 메서드)  

**특정 예외를 던져야 성공하는 경우**
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ExceptionTest {
    Class<? extends Throwable> value(); //모든 예외 타입을 수용
}

```
```java
    @ExceptionTest(ArithmeticException.class)
    public static void m1() {//성공
        int i = 0;
        i = i / i;
    }

    @ExceptionTest(ArithmeticException.class)
    public static void m2() {//실패(전달한 예외와 다른 예외)
        int[] ints = new int[0];
        int i = ints[0];
    }

    @ExceptionTest(ArithmeticException.class)
    public static void m3() {}
```
```java
    public static void main(String[] args) throws Exception {
    int tests = 0;
    int passed = 0;
    Class<?> testClass = Class.forName("org.example.item39.Sample2");
    for (Method m : testClass.getDeclaredMethods()) {
        if (m.isAnnotationPresent(ExceptionTest.class)) {
            tests++;
            try {
                m.invoke(null);
                System.out.printf("테스트 %s 실패: 예외를 던지지 않음%n", m);
            } catch (InvocationTargetException wrappedExc) {
                Throwable exc = wrappedExc.getCause();
                Class<? extends Throwable> excType = m.getAnnotation(ExceptionTest.class).value();
                if (excType.isInstance(exc)) {
                    passed++;
                } else {
                    System.out.printf("테스트 %s 실패: 기대한 예외 %s, 발생한 예외 %s%n", m, excType.getName(), exc);
                }
            } catch (Exception exc) {
                System.out.println("잘못 사용한 @ExceptionTest: " + m);
            }
        }
    }
    System.out.printf("성공: %d, 실패: %d%n", passed, tests - passed);
}
    /*
    테스트 public static void org.example.item39.Sample2.m2() 실패: 기대한 예외 java.lang.ArithmeticException, 발생한 예외 java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
    테스트 public static void org.example.item39.Sample2.m3() 실패: 예외를 던지지 않음
    성공: 1, 실패: 2
     */
```
- 애너테이션의 매개변수 값을 추출해서 올바른 예외를 던지는지 확인  

**매개변수 여러 개를 받는 경우**  
1) 배열 매개변수를 활용
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ExceptionsTest {
    Class<? extends Throwable>[] value();
}
```
```java
  @ExceptionsTest({IndexOutOfBoundsException.class, NullPointerException.class})
    public static void doublyBad() {
        List<String> list = new ArrayList<>();
        list.addAll(5, null);
    }
```
- 원소가 여럿인 배열을 지정할 때는 원소들을 중괄호로 감싸고 쉼표를 통해 구분해주면 된다.
```java
    if (m.isAnnotationPresent(ExceptionsTest.class)) {
      tests++;
      try {
        m.invoke(null);
        System.out.printf("테스트 %s 실패: 예외를 던지지 않음%n", m);
      } catch (InvocationTargetException wrappedExc) {
        Throwable exc = wrappedExc.getCause();
        int oldPassed = passed;
        Class<? extends Throwable>[] excTypes = m.getAnnotation(ExceptionsTest.class).value();
        for (Class<? extends Throwable> excType : excTypes) {
          if (excType.isInstance(exc)) {
            passed++;
            break;
          }
        }
```
2) @Repeatable 애너테이션 활용
- @Repeatable을 단 애너테이션을 반환하는 컨테이너 애너테이션 정의
- @Repeatable에 이 컨테이너 애터네이션의 class 객체를 매개변수로 전달
- 컨테이너 애너테이션은 내부 애너테이션 타입 배열을 value로 가지고 있어야 한다.
- 컨테이너 애너테이션은 보존기간과 적용범위를 명시해야 한다.(Retention, Target)

```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@Repeatable(ExceptionContainer.class)
public @interface Exceptions {
    Class<? extends Throwable> value();
}
```
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ExceptionContainer {
  Exceptions[] value();
}
```
```java
Class<?> testClass = Class.forName("org.example.item39.Sample4");

  for (Method m : testClass.getDeclaredMethods()) {
    if (m.isAnnotationPresent(Exceptions.class) || m.isAnnotationPresent(ExceptionContainer.class)) {
      cnt++;
```
- isAnnotaionPresent로 반복 가능 애너테이션과 컨테이너 애너테이션 모두 검증해야 한다.
  - 하나의 애너테이션만 달린 경우, isAnnotaionPresent(컨테이너) -> false
  - 복수의 애너테이션이 달린 경우, isAnnotaionPresent(반복 가능 애너테이션) -> false
```java
    try {
        m.invoke(null);
        System.out.printf("test %s fail: 예외를 던지지 않음%n", m);
      }catch (InvocationTargetException e) {
        Throwable exc = e.getCause();
        int oldPassed = passed;
        Exceptions[] excTypes = m.getAnnotationsByType(Exceptions.class);
        for (Exceptions excType : excTypes) {
          if (excType.value().isInstance(exc)) {
            passed++;
            break;
          } 
```
